# ----------------------------
# Set NAME to the program name
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# Set COMPRESSED to "YES" to create a compressed program
# ----------------------------

NAME        = TRICARDS
ICON        = iconc.png
DESCRIPTION = "It's like there's 3x3 cards"
COMPRESSED  = NO
COMPRESSED_MODE = zx0
HAS_PRINTF  = NO
ARCHIVED    = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)
